### ISSUE TITLE
construccion de la ventana 1 primera parte 

### ISSUE THREAD

**Issue by DiegoLopezVillegas** [DiegoLopezVillegas/Clase9#1]
construir la ventana 1 y hacer el formulario para ingresar la información del cliente

**Comment by cristiang98** [comment]
ya estoy viendo los videos, empiezo desde el primero y le voy avisando

**Comment by DiegoLopezVillegas** [comment]
listo trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1 py el formulario de registro del usuario
