### ISSUE TITLE
Funcionalidad de la ventana para mostrar los usuarios registrados en forma de items

### ISSUE THREAD

**Issue by DiegoLopezVillegas** [DiegoLopezVillegas/Clase9#14]
Favor construir una ventana para ver los usuario que se han registrado. debe mostrar los botones en forma de items de a 3 por fila y cada boton debe mostrar la cedula del usuario registrado 
hacer el boton para navegar de la ventana1.py a esta nueva ventana2.py y de esta nueva ventana2.py hacer el boton para volver a la ventana1.py

**Comment by cristiang98** [comment]
ya subi se resolvio el issue # 14 y se subio a github por favor revisar
